language: node_js
node_js: stable
cache:
  directories:
  - node_modules
branches:
  only:
  - main
install:
- npm install -g yarn
- yarn install
script:
- yarn build
after_success:
- rm -rf root@82.157.146.59:/data/www/profile-site/*
- scp -o stricthostkeychecking=no -r ./dist/* root@82.157.146.59:/data/www/profile-site/*
before_install:
- openssl aes-256-cbc -K $encrypted_7247aa035ce4_key -iv $encrypted_7247aa035ce4_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
